version: 2

jobs:
  build:
    docker:
      - image: felicianotech/docker-hugo:latest
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo -v -s ~/project/
#      - run:
#          name: "Test Website"
#          command: htmlproofer ~/project/public --allow-hash-href --check-html --empty-alt-ignore --disable-external
      - run:
          name: "Push to Server"
          command: rsync -rltgoDzO -vvv --no-p --del -e "ssh -p $PORT_NUM -o StrictHostKeyChecking=no" ~/project/public/ $USERNAME@$HOSTNAME:$DOCUMENT_ROOT

test:
  override:
    - echo "no tests are needed"
