baseURL = "https://blog.geckour.com/"
languageCode = "ja-jp"
title = "網戸の裏"
theme = "hugo-theme-cactus-plus"
hasCJKLanguage = true
googleAnalytics = "G-YRD9L1EN0J"
preserveTaxonomyNames = true

[params]
  description = "技術的な話とかチラシの裏な話とか"
  author = "geckour"
  name = "geckour"
  bio = "へっぽこ Android エンジニア"
  twitter = "geckour"
  enableRSS = true
  enableShare = true
  enableDisqus = true
  disqusShortname = "wang-hu-noli"
  enableTwitterCard = true
  iconFont = "font-awesome"
  socialIconStyle = "circle"

[social]
  twitter = "https://twitter.com/geckour"
  github = "https://github.com/geckour"

[blackfriday]
  smartypants = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
