baseURL = "http://geckour.orz.hm/blog"
canonifyURLs = true # サブパス運用時のみ設定
languageCode = "ja-jp"
title = "網戸の裏"
theme = "hugo-theme-cactus-plus"
hasCJKLanguage = true
googleAnalytics = "UA-57727105-3"

[params]
  description = "技術的な話とかチラシの裏な話とか"
  author = "geckour"
  name = "geckour"
  bio = "へっぽこAndroidエンジニア"
  twitter = "geckour"
  enableRSS = true
  iconFont = "font-awesome"
  socialIconStyle = "circle"
  ignoreFiles = ["content/about.md"]

[social]
  twitter = "https://twitter.com/geckour"
  github = "https://github.com/geckour"
