version: 2
jobs:
  deploy:
    docker:
      - image: felicianotech/docker-hugo:latest
      - image: circleci/node:10.7
    parallelism: 4
    working_directory: ~/project
    steps:
      - checkout
      - run:
        name: npm install
        command: npm install --save-dev firebase-tools
      - run:
        name: build hugo
        command: HUGO_ENV=production hugo -v -s ~/project/
      - run:
        name: deploy to Firebase Hosting
        command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
        
workflows:
  version: 2
  deploy_master:
    jobs:
      - deploy:
        filters:
          branches:
            only: master
