version: 2
jobs:
  build:
    docker:
      - image: klakegg/hugo:latest
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: build hugo
          command: HUGO_ENV=production hugo -v -s ~/project/
      - persist_to_workspace:
          root: public
          paths: .
    # The resource_class feature allows configuring CPU and RAM resources for each job. Different resource classes are available for different executors. https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: large
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install --save-dev firebase-tools
      - attach_workspace:
          at: public
      - run:
          name: deploy to Firebase Hosting
          command: ./node_modules/.bin/firebase deploy --only hosting
            --token=$FIREBASE_TOKEN

workflows:
  version: 2
  build_and_deploy_if_master:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
